### ISSUE TITLE
Extract files

### ISSUE THREAD

**Issue by ewilan-riviere** [selective-php/rar#2]
I used PHP Rar package to extract some files from `.rar` archive. I would to use this package instead but I've a problem about extract.

With [PECL Rar package](https://www.php.net/manual/en/book.rar.php)

```php
<?php

use RarArchive;

$zip = RarArchive::open($this->engine->file_path);
$path = public_path('storage/cache');

foreach ($zip->getEntries() as $key => $entry) {
    $name = $entry->getName();
    $ext = pathinfo($name, PATHINFO_EXTENSION);

    $path = "{$path}/{$this->engine->file_name}.{$ext}";
    $entry->extract($path, $xml_path);
}
```

How can I extract files with this package?

```php
<?php

use Selective\Rar\RarFileReader;
use SplFileObject;

$rar_file = new SplFileObject($this->engine->file_path);
$archive = new RarFileReader();
$rar = $archive->openFile($rar_file);

foreach ($rar->getEntries() as $entry) {
    $name = $entry->getName();
}
```

**Comment by odan** [comment]
Hi! I'm sorry, this packages is not a full PECL rar extension replacement, because it does not provide an `extract` method. The current use case of this package is to read some metadata (file listings, file size etc.) from a RAR archive.

**Comment by ewilan-riviere** [comment]
Okay! Thanks for these details 😊
