### ISSUE TITLE
Hello, Is this a bug?

### ISSUE THREAD

**Issue by nottellyou** [selective-php/rar#3]
Hello, Is this a bug?

     The format string contains errors
     Please see the attachment.

![snipaste20230511_102827](https://github.com/selective-php/rar/assets/8598743/19f7e4d7-7de2-4ecc-9fcf-437cc0e973be)
![snipaste20230511_102754](https://github.com/selective-php/rar/assets/8598743/29a1e98b-7c5c-4311-b3f4-c9a1f66efb69)

**Comment by odan** [comment]
I don't know what this is. Can you please show me a some PHP code?

**Comment by nottellyou** [comment]
vendor/selective/rar/src/RarFileReader.php

```
    private function unpack(string $format, string $data): array
    {
        $result = unpack($format, $data);

        if ($result === false) {
            throw new UnexpectedValueException('The format string contains errors');
        }

        return (array)$result;
    }
```

I think it might be because of encoding problem, because there are Chinese characters

**Comment by odan** [comment]
I guess this encoding is not supported.

**Comment by nottellyou** [comment]
@odan Yes, I think it should not support this character set, how can we support it?

**Comment by odan** [comment]
I discovered that the problem was not with the special characters. Your file was probably a RAR file created in RAR format 5. I have implemented the RAR format 5 for this package. Please update the dependency in your composer.json to version "^0.3" to make the change take effect.
